### ISSUE TITLE
Mouvement plus simple

### ISSUE THREAD

**Issue by jojolatina** [SirLynix/MiniChess#1]
Bonjour (ou bonsoir il est tard actuellement brrr~), c'est moi JS hihihi, je suis tombée sur votre live et du coup je me suis retrouvée ici. Alors c'est pas pour critiquer ou quoi que ce soit, c'est pour dire un truc constructif.

Dans la classe Window je trouve que le constructeur et l'opérateur de mouvement sont un peu codés "en dur" car il faut mettre tous les champs manuellement. Du coup je vous propose de l'implémenter comme ça :

```cpp
Window::Window(Window&& window) noexcept : Window()
{
    swap(*this, window);
}

Window& Window::operator=(Window&& window) noexcept
{
    swap(*this, window);
    return *this;
}
```

Pour faire ça il faut aussi ajouter une fonction swap et un constructeur par défaut
```cpp
void swap(Window& a, Window& b) noexcept
{
    using std::swap;
    swap(a.m_handle, b.m_handle);
}
```

Comme ça si on ajoute des champs il faut juste mettre à jour le swap.
Ah oui et en fait on peut aussi faire pareil pour le Renderer

**Comment by SirLynix** [comment]
Oui cette technique possède cet avantage, mais comme je l'ai dit en live (rapidement ceci dit), je préfère encore une autre méthode me permettant d'automatiser la chose (celle du wrapper MovablePtr que j'utilise dans Nazara notamment). On verra ça probablement à la prochaine session 😉

**Comment by jojolatina** [comment]
Ah oui c'est cool l'idée du MovablePtr !! malinx le Lyn(i)x
